# Generated by Django 5.1.2 on 2024-10-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_created_at_user_updated_at_referralcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralcode",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="является активным"),
        ),
    ]
